import { readdirSync, readFileSync } from "node:fs";
import ts from "typescript";
import { describe, expect, it } from "vitest";
import { REVIEW_DECODER_ABIS, splitAbiModules } from "./splitAbiModules.js";

const abi = `[
  { type: 'function', name: 'pay', inputs: [], outputs: [] },
] as const`;
const declaration = (name: string) => `export const ${name} = ${abi}`;

describe("review decoder ABI modules", () => {
  it("moves each named ABI to its own module and re-exports it in place", () => {
    const source = [
      declaration("jbControllerAbi"),
      declaration("jbControllerV5Abi"),
      declaration("jbRouterTerminalGatewayAbi"),
    ].join("\n\n");

    const split = splitAbiModules(source, [
      "jbControllerAbi",
      "jbRouterTerminalGatewayAbi",
    ]);

    expect(split.source).toBe(
      [
        "export { jbControllerAbi } from './abi/jbControllerAbi.js'",
        declaration("jbControllerV5Abi"),
        "export { jbRouterTerminalGatewayAbi } from './abi/jbRouterTerminalGatewayAbi.js'",
      ].join("\n\n"),
    );
    expect(Object.keys(split.modules)).toEqual([
      "jbControllerAbi",
      "jbRouterTerminalGatewayAbi",
    ]);
    expect(split.modules.jbControllerAbi).toMatch(
      /^\/\/ Generated by scripts\/addJBProjectDeploymentAddresses\.ts\. Do not edit\./,
    );
    expect(split.modules.jbControllerAbi).toContain(
      `\n\n${declaration("jbControllerAbi")}\n`,
    );
  });

  it("refuses a name the generated bindings do not declare", () => {
    expect(() =>
      splitAbiModules(declaration("jbControllerAbi"), ["jbControllerV9Abi"]),
    ).toThrow("The generated bindings have no jbControllerV9Abi.");
  });

  it("is the set the decoder reads, each from its own module", () => {
    const source = ts.createSourceFile(
      "src/review/decode.ts",
      readFileSync("src/review/decode.ts", "utf8"),
      ts.ScriptTarget.Latest,
      true,
    );
    const generated: [string, string][] = [];
    for (const statement of source.statements) {
      if (
        !ts.isImportDeclaration(statement) ||
        !ts.isStringLiteral(statement.moduleSpecifier) ||
        !statement.moduleSpecifier.text.startsWith("../generated/")
      ) {
        continue;
      }
      const bindings = statement.importClause?.namedBindings;
      for (const element of bindings && ts.isNamedImports(bindings)
        ? bindings.elements
        : []) {
        if (element.name.text.endsWith("Abi")) {
          generated.push([element.name.text, statement.moduleSpecifier.text]);
        }
      }
    }
    expect(generated.map(([name]) => name).sort()).toEqual(
      [...REVIEW_DECODER_ABIS].sort(),
    );
    for (const [name, specifier] of generated) {
      expect(specifier).toBe(`../generated/abi/${name}.js`);
    }
    expect(readdirSync("src/generated/abi").sort()).toEqual(
      REVIEW_DECODER_ABIS.map((name) => `${name}.ts`).sort(),
    );
  });
});
