/**
 * The generated ABIs the review decoder (`src/review/decode.ts`) reads. Each
 * gets a module of its own under `src/generated/abi/`, re-exported from
 * `juicebox.ts`.
 *
 * A bundler keeps every export of a module that any chunk uses, in the chunk
 * that loads the module. The decoder loads lazily, but `juicebox.ts` loads with
 * the first page, so an ABI only the decoder read rode along with every page.
 * In a module of its own, an ABI loads only with the chunks that use it.
 */
export const REVIEW_DECODER_ABIS = [
  "jbBuybackHookAbi",
  "jbBuybackHookRegistryAbi",
  "jbControllerAbi",
  "jbDirectoryAbi",
  "jbMultiTerminalAbi",
  "jbPermissionsAbi",
  "jbProjectsAbi",
  "jbRouterTerminalGatewayAbi",
  "jbRouterTerminalRegistryAbi",
  "jbSplitsAbi",
  "jbTokensAbi",
] as const;

const HEADER = `// Generated by scripts/addJBProjectDeploymentAddresses.ts. Do not edit.
// The review decoder reads this ABI, so it has a module of its own: a page
// that imports other ABIs from the SDK does not load it.
`;

/**
 * Move each named `export const <name> = [...] as const` out of the generated
 * source into a module of its own, leaving a re-export in its place. Throws
 * when a name is missing, so a renamed contract cannot silently drop out.
 */
export function splitAbiModules(
  source: string,
  names: readonly string[],
): { source: string; modules: Record<string, string> } {
  const modules: Record<string, string> = {};
  let rest = source;
  for (const name of names) {
    const declaration = new RegExp(
      `^export const ${name} = \\[[\\s\\S]*?^\\] as const;?$`,
      "m",
    );
    const match = rest.match(declaration);
    if (!match) throw new Error(`The generated bindings have no ${name}.`);
    modules[name] = `${HEADER}\n${match[0]}\n`;
    rest = rest.replace(
      declaration,
      `export { ${name} } from './abi/${name}.js'`,
    );
  }
  return { source: rest, modules };
}
