import { describe, expect, test } from "vitest";
import * as sdk from "./index.js";
import * as safe from "./safe.js";
import * as v6 from "./v6/index.js";

describe("published core SDK surfaces", () => {
  test("exports the framework-free Safe creation boundary", () => {
    expect(safe.resolveSafeAddress).toBeTypeOf("function");
    expect(safe.buildSafeDeploymentTx).toBeTypeOf("function");
    expect(safe.bundleSafeLaunch).toBeTypeOf("function");
    expect(safe.verifySafeDeployments).toBeTypeOf("function");
    expect(safe.SAFE_PROXY_CREATION_CODE).toMatch(/^0x(?:[\da-f]{2}){486}$/u);
  });

  test("exports the framework-free utility and V6 transaction boundaries", () => {
    expect(sdk.getTokenAToBQuote).toBeTypeOf("function");
    expect(sdk.getProjectTerminalStore).toBeTypeOf("function");
    expect(sdk.downsampleTimeSeries).toBeTypeOf("function");
    expect(sdk.requestBendystraw).toBeTypeOf("function");
    expect(sdk.resolveBendystrawNetwork).toBeTypeOf("function");
    expect(sdk.selectBendystrawEndpoint).toBeTypeOf("function");
    expect(sdk.bendystrawDataHasFields).toBeTypeOf("function");
    expect(sdk.bendystrawCacheTtl).toBeTypeOf("function");
    expect(sdk.bendystrawProjectRefsFilter).toBeTypeOf("function");
    expect(sdk.bendystrawProjectRefsFilters).toBeTypeOf("function");
    expect(sdk.createJBCenterClient).toBeTypeOf("function");
    expect(sdk.createJBCenterRpcProvider).toBeTypeOf("function");
    expect(sdk.JBCENTER_DEFAULT_URL).toBe("https://juicebox.center");
    expect(sdk.JBCENTER_RPC_METHODS).toContain("eth_chainId");
    expect(sdk.JBCENTER_SPONSORED_CHAIN_IDS).toContain(8453);
    expect(sdk.isSponsorable).toBeTypeOf("function");
    expect(sdk.sponsorableChains).toBeTypeOf("function");
    expect(sdk.unsponsoredChains).toBeTypeOf("function");
    expect(sdk.decodeDeploymentCall).toBeTypeOf("function");
    expect(sdk.intentCalls).toBeTypeOf("function");
    expect(sdk.mergeSearch).toBeTypeOf("function");
    expect(sdk.intentRow).toBeTypeOf("function");
    expect(sdk.intentPath).toBeTypeOf("function");
    expect(sdk.deployedChains).toBeTypeOf("function");
    expect(sdk.isFullyDeployed).toBeTypeOf("function");
    expect(sdk.ensureDeployed).toBeTypeOf("function");
    expect(sdk.EnsureDeployedError).toBeTypeOf("function");
    expect(sdk.publishSignedIntent).toBeTypeOf("function");
    expect(sdk.JBCenterIntentMismatchError).toBeTypeOf("function");
    expect(sdk.describeCenterRefusal).toBeTypeOf("function");
    expect(sdk.describeCenterRefusal(new Error("boom"))).toBeNull();
    expect(v6.buildDeployRevnetTx).toBeTypeOf("function");
    expect(v6.buildAutoIssueTx).toBeTypeOf("function");
    expect(v6.quoteDirectPaySwap).toBeTypeOf("function");
    expect(v6.buildDirectPaySwapTx).toBeTypeOf("function");
    expect(v6.permit2TypedData).toBeTypeOf("function");
    expect(v6.netLoanProceeds).toBeTypeOf("function");
    expect(v6.build721RulesetMetadata).toBeTypeOf("function");
    expect(v6.decode721RulesetMetadata).toBeTypeOf("function");
    expect(sdk.isContractRevertError).toBeTypeOf("function");
    expect(sdk.isMissingContractFunctionError).toBeTypeOf("function");
    expect(v6.requiredFeedPairs).toBeTypeOf("function");
    expect(v6.probeFeedReachability).toBeTypeOf("function");
    expect(v6.REV_METADATA_ALLOW_SUCKER_DEPLOYMENT).toBe(1 << 2);
    expect(v6.REVLOANS_BURN_PERMISSION_ID).toBe(11);
  });
});
